---
- name: Get server uptime
  hosts: home, localhost

  ignore_unreachable: true

  tasks:
  - name: Get uptime first
    shell: uptime
    ignore_errors: true
    register: hello
  - debug: msg="{{ hello.stdout }}"

