---
- hosts: localhost
  connection: local

  tasks:
    - name: Ensure Docker image is built from the test Dockerfile.
      docker_image:
        name: test
        source: build
        build:
          path: test
          pull: yes
        state: present

    - name: Ensure the test container is running.
      docker_container:
        image: test:latest
        name: test
        state: started
        container_default_behavior: no_defaults
